# Generated by Django 5.2.5 on 2025-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='web_development_photos/')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
    ]
