# Generated by Django 5.2.5 on 2025-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdevelopment',
            name='photo',
            field=models.ImageField(upload_to='ds&da/'),
        ),
    ]
