# Generated by Django 5.2.5 on 2025-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_alter_webdevelopment_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_ML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='aiml/')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DATA_SCIENCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ds&da/')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='webdevelopment',
            name='photo',
            field=models.ImageField(upload_to='web_development_photos/'),
        ),
    ]
