# Generated by Django 5.2.5 on 2025-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0003_ai_ml_data_science_alter_webdevelopment_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='pythonproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pythonproject/')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
            ],
        ),
    ]
