# Generated by Django 5.2.5 on 2025-08-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0006_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
