# Generated by Django 5.2.5 on 2025-08-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0007_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_ml',
            name='photo',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='data_science',
            name='photo',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pythonproject',
            name='photo',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='webdevelopment',
            name='photo',
            field=models.BinaryField(),
        ),
    ]
