# Generated by Django 5.2.5 on 2025-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0008_alter_ai_ml_photo_alter_data_science_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_ml',
            name='photo',
            field=models.ImageField(upload_to='aiml/'),
        ),
        migrations.AlterField(
            model_name='data_science',
            name='photo',
            field=models.ImageField(upload_to='ds&da/'),
        ),
        migrations.AlterField(
            model_name='pythonproject',
            name='photo',
            field=models.ImageField(upload_to='pythonproject/'),
        ),
        migrations.AlterField(
            model_name='webdevelopment',
            name='photo',
            field=models.ImageField(upload_to='web_development_photos/'),
        ),
    ]
